### ISSUE TITLE
don't have armor trims to shine

### ISSUE THREAD

**Issue by Qiufengluoyes** [devendrn/newb-x-mcbe#11]
version:
Minecraft 1.20.50
newb-x 15.21
don't have armor trims to shine
![Screenshot_2024-02-09-14-47-48-427_com mojang minecraftpe](https://github.com/devendrn/newb-x-mcbe/assets/106154525/4d67657b-b9a9-427e-bd37-86f658cdbb7c)
![Screenshot_2024-02-09-14-33-36-956_com mojang minecraftpe](https://github.com/devendrn/newb-x-mcbe/assets/106154525/6aea347b-b021-4356-9dd1-98682a597c8e)

**Comment by IndeedItzGab** [comment]
It's actually not supported for glow armor trim, however if you want something like that, there's a certain texture pack in mcpedl you can find.

**Comment by Qiufengluoyes** [comment]
> It's actually not supported for glow armor trim, however if you want something like that, there's a certain texture pack in mcpedl you can find.

I know,thanks.
