### ISSUE TITLE
Not supported for 1.21

### ISSUE THREAD

**Issue by Exotic123492** [devendrn/newb-x-mcbe#18]
The whole world becomes invisible when a shader is activated.

**Comment by Enoughrise** [comment]
then use this
https://discord.com/channels/844591537430069279/1125004721585934356/1247734648092758137

**Comment by devendrn** [comment]
Closing this since support for 1.21 has been added in laz branch. 
Changes might be back ported to mbt branch if there are still users who prefer using old build system.
