### ISSUE TITLE
Errors in vertex.sc

### ISSUE THREAD

**Issue by gamce3** [devendrn/newb-x-mcbe#22]
In the line of the file where this parameter is mentioned 

  vec3 light = nlActorLighting(a_position, a_normal, World, TileLightColor, OverlayColor, newFog, nether, underWater, end, ViewPositionAndTime.w);

It causes an error to appear when executing the ./build.sh pack command

If this entire line is deleted, the following message will appear Error `light' undeclared

![Screenshot_20240713-205939](https://github.com/user-attachments/assets/504fb686-9db4-46a3-98bd-02f2166e9666)
![Screenshot_20240713-210250](https://github.com/user-attachments/assets/4b62790d-82ff-40c7-9c23-f8c6aceb7da2)

**Comment by devendrn** [comment]
Thanks for letting me know. It should be fixed now.
