### ISSUE TITLE
Lazurite bug

### ISSUE THREAD

**Issue by xxchizaxx** [devendrn/newb-x-mcbe#25]
Unable to build Shaders due to Lazurite plugin update to version 0.3.0 
![Screenshot_20240726-000016_Termux](https://github.com/user-attachments/assets/ea46d70d-bc2d-4c14-b489-ab436a7834f1)

**Comment by devendrn** [comment]
Use older version for now. Supported version is mentioned in `requirements.txt`
```
pip install -r requirements.txt
```

**Comment by gamce3** [comment]
We already found the solution, a guy on the discord suggested that we uninstall lazurite and install it with pip install lazurite==0.2.1
